import type { StarPoint } from './umap.worker';

// Pre-positioned demo repos for the landing page galaxy
// Positions manually tuned to form believable semantic clusters
export const DEMO_STARS: StarPoint[] = [
	// ── Frontend cluster (top-left) ───────────────────────────────────────
	{ id: 1, full_name: 'facebook/react', name: 'react', owner_login: 'facebook', owner_avatar: 'https://avatars.githubusercontent.com/u/69631?v=4', description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.', html_url: 'https://github.com/facebook/react', language: 'JavaScript', topics: ['javascript', 'frontend', 'ui'], stars_count: 229000, forks_count: 46000, starred_at: '2022-01-10T00:00:00Z', x: 0.12, y: 0.18, cluster: 0, clusterLabel: 'frontend · javascript' },
	{ id: 2, full_name: 'vuejs/vue', name: 'vue', owner_login: 'vuejs', owner_avatar: 'https://avatars.githubusercontent.com/u/6128107?v=4', description: 'Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.', html_url: 'https://github.com/vuejs/vue', language: 'TypeScript', topics: ['javascript', 'frontend', 'framework'], stars_count: 207000, forks_count: 33000, starred_at: '2022-03-15T00:00:00Z', x: 0.08, y: 0.24, cluster: 0, clusterLabel: 'frontend · javascript' },
	{ id: 3, full_name: 'sveltejs/svelte', name: 'svelte', owner_login: 'sveltejs', owner_avatar: 'https://avatars.githubusercontent.com/u/23617963?v=4', description: 'Cybernetically enhanced web apps', html_url: 'https://github.com/sveltejs/svelte', language: 'TypeScript', topics: ['javascript', 'frontend', 'compiler'], stars_count: 80000, forks_count: 4300, starred_at: '2023-02-20T00:00:00Z', x: 0.16, y: 0.14, cluster: 0, clusterLabel: 'frontend · javascript' },
	{ id: 4, full_name: 'tailwindlabs/tailwindcss', name: 'tailwindcss', owner_login: 'tailwindlabs', owner_avatar: 'https://avatars.githubusercontent.com/u/67109815?v=4', description: 'A utility-first CSS framework for rapid UI development.', html_url: 'https://github.com/tailwindlabs/tailwindcss', language: 'JavaScript', topics: ['css', 'frontend', 'utility'], stars_count: 83000, forks_count: 4200, starred_at: '2022-06-01T00:00:00Z', x: 0.06, y: 0.10, cluster: 0, clusterLabel: 'frontend · javascript' },
	{ id: 5, full_name: 'vitejs/vite', name: 'vite', owner_login: 'vitejs', owner_avatar: 'https://avatars.githubusercontent.com/u/65625612?v=4', description: 'Next generation frontend tooling. It\'s fast!', html_url: 'https://github.com/vitejs/vite', language: 'TypeScript', topics: ['frontend', 'build-tool', 'javascript'], stars_count: 68000, forks_count: 6100, starred_at: '2023-04-10T00:00:00Z', x: 0.20, y: 0.22, cluster: 0, clusterLabel: 'frontend · javascript' },

	// ── AI / ML cluster (top-right) ──────────────────────────────────────
	{ id: 6, full_name: 'pytorch/pytorch', name: 'pytorch', owner_login: 'pytorch', owner_avatar: 'https://avatars.githubusercontent.com/u/21003710?v=4', description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration', html_url: 'https://github.com/pytorch/pytorch', language: 'Python', topics: ['deep-learning', 'machine-learning', 'python'], stars_count: 83000, forks_count: 22000, starred_at: '2021-11-05T00:00:00Z', x: 0.82, y: 0.15, cluster: 1, clusterLabel: 'machine learning · python' },
	{ id: 7, full_name: 'tensorflow/tensorflow', name: 'tensorflow', owner_login: 'tensorflow', owner_avatar: 'https://avatars.githubusercontent.com/u/15658638?v=4', description: 'An Open Source Machine Learning Framework for Everyone', html_url: 'https://github.com/tensorflow/tensorflow', language: 'Python', topics: ['deep-learning', 'machine-learning', 'neural-network'], stars_count: 186000, forks_count: 74000, starred_at: '2021-09-12T00:00:00Z', x: 0.88, y: 0.20, cluster: 1, clusterLabel: 'machine learning · python' },
	{ id: 8, full_name: 'huggingface/transformers', name: 'transformers', owner_login: 'huggingface', owner_avatar: 'https://avatars.githubusercontent.com/u/25720743?v=4', description: 'Transformers: State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX.', html_url: 'https://github.com/huggingface/transformers', language: 'Python', topics: ['nlp', 'deep-learning', 'transformers'], stars_count: 135000, forks_count: 26000, starred_at: '2023-01-18T00:00:00Z', x: 0.79, y: 0.10, cluster: 1, clusterLabel: 'machine learning · python' },
	{ id: 9, full_name: 'langchain-ai/langchain', name: 'langchain', owner_login: 'langchain-ai', owner_avatar: 'https://avatars.githubusercontent.com/u/126733545?v=4', description: 'Build context-aware reasoning applications', html_url: 'https://github.com/langchain-ai/langchain', language: 'Python', topics: ['llm', 'ai', 'agents'], stars_count: 92000, forks_count: 14000, starred_at: '2023-06-22T00:00:00Z', x: 0.86, y: 0.08, cluster: 1, clusterLabel: 'machine learning · python' },

	// ── Systems / Rust cluster (bottom-right) ───────────────────────────
	{ id: 10, full_name: 'rust-lang/rust', name: 'rust', owner_login: 'rust-lang', owner_avatar: 'https://avatars.githubusercontent.com/u/5430905?v=4', description: 'Empowering everyone to build reliable and efficient software.', html_url: 'https://github.com/rust-lang/rust', language: 'Rust', topics: ['rust', 'systems', 'compiler'], stars_count: 96000, forks_count: 12000, starred_at: '2022-08-14T00:00:00Z', x: 0.85, y: 0.78, cluster: 2, clusterLabel: 'systems · rust' },
	{ id: 11, full_name: 'BurntSushi/ripgrep', name: 'ripgrep', owner_login: 'BurntSushi', owner_avatar: 'https://avatars.githubusercontent.com/u/227717?v=4', description: 'ripgrep recursively searches directories for a regex pattern while respecting your gitignore', html_url: 'https://github.com/BurntSushi/ripgrep', language: 'Rust', topics: ['rust', 'grep', 'cli'], stars_count: 48000, forks_count: 2000, starred_at: '2022-11-30T00:00:00Z', x: 0.80, y: 0.84, cluster: 2, clusterLabel: 'systems · rust' },
	{ id: 12, full_name: 'alacritty/alacritty', name: 'alacritty', owner_login: 'alacritty', owner_avatar: 'https://avatars.githubusercontent.com/u/42165677?v=4', description: 'A cross-platform, OpenGL terminal emulator.', html_url: 'https://github.com/alacritty/alacritty', language: 'Rust', topics: ['terminal', 'rust', 'gpu'], stars_count: 56000, forks_count: 3000, starred_at: '2021-12-08T00:00:00Z', x: 0.90, y: 0.72, cluster: 2, clusterLabel: 'systems · rust' },
	{ id: 13, full_name: 'ziglang/zig', name: 'zig', owner_login: 'ziglang', owner_avatar: 'https://avatars.githubusercontent.com/u/42537337?v=4', description: 'General-purpose programming language designed for robustness, optimality, and maintainability.', html_url: 'https://github.com/ziglang/zig', language: 'Zig', topics: ['zig', 'systems', 'compiler'], stars_count: 35000, forks_count: 2600, starred_at: '2024-01-15T00:00:00Z', x: 0.78, y: 0.70, cluster: 2, clusterLabel: 'systems · rust' },

	// ── CLI / Terminal tools cluster (bottom-left) ──────────────────────
	{ id: 14, full_name: 'junegunn/fzf', name: 'fzf', owner_login: 'junegunn', owner_avatar: 'https://avatars.githubusercontent.com/u/700826?v=4', description: 'A command-line fuzzy finder', html_url: 'https://github.com/junegunn/fzf', language: 'Go', topics: ['cli', 'fuzzy-finder', 'terminal'], stars_count: 64000, forks_count: 2400, starred_at: '2020-05-22T00:00:00Z', x: 0.14, y: 0.80, cluster: 3, clusterLabel: 'cli · terminal' },
	{ id: 15, full_name: 'sharkdp/bat', name: 'bat', owner_login: 'sharkdp', owner_avatar: 'https://avatars.githubusercontent.com/u/4209558?v=4', description: 'A cat(1) clone with wings.', html_url: 'https://github.com/sharkdp/bat', language: 'Rust', topics: ['cli', 'terminal', 'rust'], stars_count: 49000, forks_count: 1300, starred_at: '2021-07-19T00:00:00Z', x: 0.08, y: 0.86, cluster: 3, clusterLabel: 'cli · terminal' },
	{ id: 16, full_name: 'charmbracelet/bubbletea', name: 'bubbletea', owner_login: 'charmbracelet', owner_avatar: 'https://avatars.githubusercontent.com/u/68166023?v=4', description: 'A powerful little TUI framework.', html_url: 'https://github.com/charmbracelet/bubbletea', language: 'Go', topics: ['tui', 'cli', 'go'], stars_count: 28000, forks_count: 800, starred_at: '2023-03-10T00:00:00Z', x: 0.18, y: 0.88, cluster: 3, clusterLabel: 'cli · terminal' },
	{ id: 17, full_name: 'jesseduffield/lazygit', name: 'lazygit', owner_login: 'jesseduffield', owner_avatar: 'https://avatars.githubusercontent.com/u/8456633?v=4', description: 'simple terminal UI for git commands', html_url: 'https://github.com/jesseduffield/lazygit', language: 'Go', topics: ['git', 'tui', 'cli'], stars_count: 52000, forks_count: 1900, starred_at: '2022-09-04T00:00:00Z', x: 0.22, y: 0.76, cluster: 3, clusterLabel: 'cli · terminal' },

	// ── Backend / Database cluster (center-right) ───────────────────────
	{ id: 18, full_name: 'supabase/supabase', name: 'supabase', owner_login: 'supabase', owner_avatar: 'https://avatars.githubusercontent.com/u/54469796?v=4', description: 'The open source Firebase alternative.', html_url: 'https://github.com/supabase/supabase', language: 'TypeScript', topics: ['database', 'backend', 'postgres'], stars_count: 73000, forks_count: 7100, starred_at: '2023-05-12T00:00:00Z', x: 0.62, y: 0.45, cluster: 4, clusterLabel: 'backend · database' },
	{ id: 19, full_name: 'prisma/prisma', name: 'prisma', owner_login: 'prisma', owner_avatar: 'https://avatars.githubusercontent.com/u/17219288?v=4', description: 'Next-generation ORM for Node.js & TypeScript', html_url: 'https://github.com/prisma/prisma', language: 'TypeScript', topics: ['orm', 'database', 'typescript'], stars_count: 39000, forks_count: 1500, starred_at: '2022-12-01T00:00:00Z', x: 0.70, y: 0.50, cluster: 4, clusterLabel: 'backend · database' },
	{ id: 20, full_name: 'trpc/trpc', name: 'trpc', owner_login: 'trpc', owner_avatar: 'https://avatars.githubusercontent.com/u/78011399?v=4', description: 'End-to-end typesafe APIs made easy', html_url: 'https://github.com/trpc/trpc', language: 'TypeScript', topics: ['typescript', 'api', 'rpc'], stars_count: 35000, forks_count: 1200, starred_at: '2023-08-15T00:00:00Z', x: 0.66, y: 0.38, cluster: 4, clusterLabel: 'backend · database' },

	// ── Dev tooling cluster (center) ──────────────────────────────────
	{ id: 21, full_name: 'microsoft/typescript', name: 'TypeScript', owner_login: 'microsoft', owner_avatar: 'https://avatars.githubusercontent.com/u/6154722?v=4', description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output.', html_url: 'https://github.com/microsoft/typescript', language: 'TypeScript', topics: ['typescript', 'compiler', 'javascript'], stars_count: 100000, forks_count: 12000, starred_at: '2021-06-20T00:00:00Z', x: 0.44, y: 0.35, cluster: 5, clusterLabel: 'tooling · typescript' },
	{ id: 22, full_name: 'biomejs/biome', name: 'biome', owner_login: 'biomejs', owner_avatar: 'https://avatars.githubusercontent.com/u/140182672?v=4', description: 'A toolchain for web projects, aimed to provide functionalities to maintain them.', html_url: 'https://github.com/biomejs/biome', language: 'Rust', topics: ['linter', 'formatter', 'typescript'], stars_count: 16000, forks_count: 500, starred_at: '2024-02-01T00:00:00Z', x: 0.38, y: 0.42, cluster: 5, clusterLabel: 'tooling · typescript' },
	{ id: 23, full_name: 'oven-sh/bun', name: 'bun', owner_login: 'oven-sh', owner_avatar: 'https://avatars.githubusercontent.com/u/104205903?v=4', description: 'Incredibly fast JavaScript runtime, bundler, test runner, and package manager – all in one', html_url: 'https://github.com/oven-sh/bun', language: 'Zig', topics: ['javascript', 'runtime', 'bundler'], stars_count: 74000, forks_count: 2200, starred_at: '2023-09-20T00:00:00Z', x: 0.50, y: 0.28, cluster: 5, clusterLabel: 'tooling · typescript' },
	{ id: 24, full_name: 'denoland/deno', name: 'deno', owner_login: 'denoland', owner_avatar: 'https://avatars.githubusercontent.com/u/42048915?v=4', description: 'A modern runtime for JavaScript and TypeScript.', html_url: 'https://github.com/denoland/deno', language: 'Rust', topics: ['javascript', 'typescript', 'runtime'], stars_count: 94000, forks_count: 5300, starred_at: '2022-04-05T00:00:00Z', x: 0.56, y: 0.22, cluster: 5, clusterLabel: 'tooling · typescript' },

	// ── Editor / Neovim cluster (center-left) ───────────────────────────
	{ id: 25, full_name: 'neovim/neovim', name: 'neovim', owner_login: 'neovim', owner_avatar: 'https://avatars.githubusercontent.com/u/6471485?v=4', description: 'Vim-fork focused on extensibility and usability', html_url: 'https://github.com/neovim/neovim', language: 'Vim Script', topics: ['vim', 'neovim', 'editor'], stars_count: 82000, forks_count: 5700, starred_at: '2020-03-18T00:00:00Z', x: 0.30, y: 0.55, cluster: 6, clusterLabel: 'editor · neovim' },
	{ id: 26, full_name: 'wez/wezterm', name: 'wezterm', owner_login: 'wez', owner_avatar: 'https://avatars.githubusercontent.com/u/117441?v=4', description: 'A GPU-accelerated cross-platform terminal emulator and multiplexer written in Rust', html_url: 'https://github.com/wez/wezterm', language: 'Rust', topics: ['terminal', 'rust', 'gpu'], stars_count: 18000, forks_count: 850, starred_at: '2024-03-12T00:00:00Z', x: 0.24, y: 0.62, cluster: 6, clusterLabel: 'editor · neovim' },
	{ id: 27, full_name: 'ohmyzsh/ohmyzsh', name: 'ohmyzsh', owner_login: 'ohmyzsh', owner_avatar: 'https://avatars.githubusercontent.com/u/22552083?v=4', description: 'A delightful community-driven framework for managing your zsh configuration.', html_url: 'https://github.com/ohmyzsh/ohmyzsh', language: 'Shell', topics: ['zsh', 'shell', 'terminal'], stars_count: 172000, forks_count: 25000, starred_at: '2019-07-04T00:00:00Z', x: 0.36, y: 0.65, cluster: 6, clusterLabel: 'editor · neovim' },

	// ── Infrastructure / DevOps cluster (top-center) ────────────────────
	{ id: 28, full_name: 'vercel/next.js', name: 'next.js', owner_login: 'vercel', owner_avatar: 'https://avatars.githubusercontent.com/u/14985020?v=4', description: 'The React Framework', html_url: 'https://github.com/vercel/next.js', language: 'JavaScript', topics: ['react', 'ssr', 'framework'], stars_count: 125000, forks_count: 26000, starred_at: '2021-03-14T00:00:00Z', x: 0.46, y: 0.12, cluster: 7, clusterLabel: 'framework · react' },
	{ id: 29, full_name: 'vercel/turborepo', name: 'turborepo', owner_login: 'vercel', owner_avatar: 'https://avatars.githubusercontent.com/u/14985020?v=4', description: 'Incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust', html_url: 'https://github.com/vercel/turborepo', language: 'Rust', topics: ['monorepo', 'build', 'javascript'], stars_count: 26000, forks_count: 1700, starred_at: '2023-11-10T00:00:00Z', x: 0.54, y: 0.08, cluster: 7, clusterLabel: 'framework · react' },
	{ id: 30, full_name: 'shadcn-ui/ui', name: 'ui', owner_login: 'shadcn-ui', owner_avatar: 'https://avatars.githubusercontent.com/u/139895814?v=4', description: 'Beautifully designed components that you can copy and paste into your apps.', html_url: 'https://github.com/shadcn-ui/ui', language: 'TypeScript', topics: ['react', 'ui', 'components'], stars_count: 75000, forks_count: 4700, starred_at: '2023-07-30T00:00:00Z', x: 0.38, y: 0.18, cluster: 7, clusterLabel: 'framework · react' },
];

export const CLUSTER_COLORS: Record<number, string> = {
	0: '#60a5fa', // blue - frontend
	1: '#a78bfa', // violet - ML/AI
	2: '#fb923c', // orange - systems
	3: '#34d399', // emerald - CLI
	4: '#38bdf8', // sky - backend
	5: '#fbbf24', // amber - tooling
	6: '#f472b6', // pink - editors
	7: '#4ade80', // green - frameworks
	8: '#e879f9', // fuchsia
	9: '#22d3ee', // cyan
	10: '#a3e635', // lime
	11: '#f87171', // red
	12: '#818cf8', // indigo
	13: '#2dd4bf', // teal
};
